### PR TITLE
added functional test for short code/ids generation.

### PR DESCRIPTION
**Pull request by mandric**
Wanted to add some kind of benchmark for the `ids` lib because I really had no clue how well it performs.

### CODE REVIEW

**Comment by SCdF** [comment]
@mandric The test looks fine (though I'm not sure why you're calling it a performance benchmark, language difference?), but I'm about to delete this generation code right? We're going to replace the whole thing with `Math.random()*(10 ^ digits)` or whatever right? Do you think the test is still relevant? Just want to make sure we're on the same page.

**Comment by SCdF** [comment]
So @mandric I merged this because I wanted to write tests around this area as well. This test actually crashes my node with an oom error. It also takes forever to do so.

I'll look into optimising it, but I think I may end up deleting it in my changes, because:
 - Unit tests should run fast and test features, not slow and test arbitrary performance
 - I shouldn't have to muck around with node heap settings to run a unit test

**Comment by mandric** [comment]
> Unit tests should run fast and test features, not slow and test arbitrary performance

It's not a unit test, that's why it's a functional test in the `tests/functional` directory.

> I shouldn't have to muck around with node heap settings to run a unit test

I didn't need to, not sure what that could be...  also the test won't need mocking when you remove the `config.get` from that function which I don't think belongs there anyway.  Not sure if that helps though.

**Comment by mandric** [comment]
> I'm about to delete this generation code right? We're going to replace the whole thing with Math.random()*(10 ^ digits) or whatever right? Do you think the test is still relevant? Just want to make sure we're on the same page.

I would keep the function because it has a nice feature of a configurable format, I see no value in throwing that away because it could be useful in the future. I would just pass it the format config as an argument and have a default of `1111`.

**Comment by SCdF** [comment]
I'm way ahead of you sorry, perils or remote development. I'm about to push the PR, we can talk over it soon

**Comment by mandric** [comment]
Sure, np!

**Pull request merged**
