### PR TITLE
Use the correct function name

### PR DESCRIPTION
**Pull request by SCdF**
Nano, not PouchDB!

medic/medic-webapp#3790
medic/medic-projects#2648

# Review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.
- [ ] Documented: Announced in Changes.md in plain English. Configuration and user documentation on [medic-docs](https://github.com/medic/medic-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.
- [ ] Webapp CI runs clean against this branch

### CODE REVIEW

**Comment by SCdF** [comment]
A note on testing. The way this would have been found would have been through more extensive manual testing (which is my fault for not doing) by generating enough documents to force it to bump the number.

It would also have been found with integration testing. Unfortunately we don't have a framework for this in sentinel right now.

It is a valid question as to whether we or do not want to introduce this framework.

**Comment by SCdF** [comment]
Actually @estellecomment don't review this yet, I've found more problems due to recent changes

**Comment by SCdF** [comment]
I've tested and confirmed that this works.

I wrote a small custom script you run from the root of sentinel, on an empty but initialised (with ddoc) DB, after modifying the `MIN_ID_LENGTH` in ids.js to `3` (So it only has to generate ~1000 docs as opposed to ~100000):

```js
const db = require('./db'),
      ids = require('./lib/ids');

const generator = ids.generator(db);

const doc = id => {return {
  type: 'person',
  patient_id: id,
  reported_date: new Date()
};};

const ITERATIONS = 10000;
let   iteration = 0;

const promiseLoop = () => {
  if (ITERATIONS !== ++iteration) {
    return loop().then(promiseLoop);
  }
};

const loop = () => generator.next().value.then(patientId => {
  const nextDoc = doc(patientId);
  console.log(`About to insert ${nextDoc.patient_id}`);
  return new Promise((resolve, reject) => db.medic.insert(nextDoc, (err, result) => {
    if (err) {
      reject(err);
    } else {
      resolve(result);
    }
  }));
});

return promiseLoop()
  .catch(console.error);
```

If you run this you can see it doing stuff like this:

```
About to insert 700
About to insert 036
About to insert 760
About to insert 784
About to insert 267
warn: Could not create a unique id of length 3, increasing length
About to insert 5903
About to insert 8310
About to insert 3773
About to insert 8941
About to insert 2343
```

I'm not sure how to formalise this kind of thing honestly. We don't want to run this test every time, even if I could re-shape it into an integration test.

**Comment by estellecomment** [comment]
Why don't you want to run that test every time? Because it's too long to run? `MIN_ID_LENGTH` = 1 would make it short enough, just loop it until it collides and check the next id has length > 1.

But yeah we don't have integration tests setup for sentinel yet. Would be nice, for transitions too, this kind of wrong db mocking is pretty common...

**Pull request merged**
