### PR TITLE
Configurable max sms per message

### PR DESCRIPTION
**Pull request by garethbowen**
medic/medic-webapp#3095

### CODE REVIEW

**Comment by garethbowen** [comment]
@mandric I'm comfortable with it because it'll only happen when truncating messages. With the default truncation limit set to 10 messages this will probably be rare.

**Comment by mandric** [comment]
Also when we make doc structure changes we need to document them somewhere.

**Comment by garethbowen** [comment]
If only we had types... </stefan>

@mandric Seeing as this documentation doesn't exist yet are you alright for me to merge this as is? It's an addition to the doc structure so it shouldn't break any integrations.

**Comment by mandric** [comment]
@garethbowen I was hoping to see at least a sprout of docs before it's merged.  I think that's part of the code review process.

**Comment by mandric** [comment]
I was also wondering a little why doc changes is needed?  I'd like to reduce them as much as possible because it increases footprint everywhere.

**Pull request merged**
